### ISSUE TITLE
bug...

### ISSUE THREAD

**Issue by wec246810** [giacomoferretti/CloudflareScraper#1]
xyz.hexile.cloudflarescraper.ScraperException: Error parsing Cloudflare IUAM Javascript challenge. Please report to @author@ [@github@].

**Comment by giacomoferretti** [comment]
Thanks for the report!
I am aware of the issue. I haven't updated the library since CloudFlare changed the challenge, so the library won't work.
There is another problem also, it cannot be used in Android, because it uses the Nashorn engine to execute JavaScript code, and that is not supported in Android.

I would like to rewrite the entire library, but I don't have much time do to so. Feel free to make a pull request.

**Comment by giacomoferretti** [comment]
I've tried updating the code, but the included Nashorn engine doesn't support some functions added in the Cloudflare challenge. We could use either Node JS or something else, but I won't update the code in the near future.
